project/project/urls.py
from accounts.views import authenticate
from bulletin.views import send_mail, successful_submission
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_send_mail/', send_mail, name='sendmail'),
    path('successful_submission/', successful_submission, name='successful_submission'),
    path('bulletin/', include('bulletin.urls')),
    path(r'ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("accounts/", include("accounts.urls")),
    path("authenticate/", authenticate, name='authenticate'),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/bulletin/models.py
import uuid

from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class AuthUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    uuid = models.UUIDField(default=uuid.uuid4)
    authenticate = models.BooleanField(default=False)


class PostCategory(models.Model):
    class Meta:
        verbose_name = u"Категория объявления"
        verbose_name_plural = u"Категории объявлений"

    name = models.CharField(max_length=100, unique=True, default=None)
    clients = models.ManyToManyField(User, related_name='categories')

    def __str__(self):
        return self.name


class Post(models.Model):
    class Meta:
        verbose_name = u"Объявление"
        verbose_name_plural = u"Объявления"

    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    dateCreation = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    TANK = 'TNK'
    HILL = 'HL'
    DD = 'DD'
    MERCHANT = 'MRCH'
    GUILDMASTER = 'GMSTR'
    QUESTGIVER = 'QGVR'
    BLACKMITH = 'BLKMTH'
    TANNER = 'TNR'
    POTION = 'PTN'
    MASTER_SPELL = 'MSTRSPL'

    CATEGORY_CHOICES = (
        (TANK, 'Танк'),
        (HILL, 'Хилл'),
        (DD, 'ДД'),
        (MERCHANT, 'Торговец'),
        (GUILDMASTER, 'Гилдмастер'),
        (QUESTGIVER, 'Квестгивер'),
        (BLACKMITH, 'Кузнец'),
        (TANNER, 'Кожевник'),
        (POTION, 'Зельевар'),
        (MASTER_SPELL, 'Мастер заклинаний'),
    )

    category = models.CharField(
        max_length=128, choices=CATEGORY_CHOICES,
        default=TANK, verbose_name='Тип'
    )
    title = models.CharField(max_length=128, verbose_name='Заголовок')
    text = RichTextUploadingField()

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.title}| {self.text[:20]}'


class Response(models.Model):
    class Meta:
        verbose_name = u"Комментарий к новости"
        verbose_name_plural = u"Комментарии к новостям"

    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Объявление')
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    text = models.TextField(verbose_name='Отклик')
    dateCreation = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    status = models.BooleanField(default=False)

    def update_status(self):
        return Response.objects.filter(id=self.id).update(status=True)

    def __str__(self):
        return f'{self.dateCreation} {self.text} {self.commentUser}'

project/templates/delete_news.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1 xmlns="http://www.w3.org/1999/html">Удаление новости: {{ object.title }}</h1>
<hr>
<dialog open>
   <div>
            <form action="" method="post">
                {% csrf_token %}
                <p>Удаляем "{{ object.title }}"?</p>
                <p><input type="submit" value="Удалить" /></p>
            </form>

                <button onclick="window.location='http://127.0.0.1:8000/news/'">Отменить</button>
   </div>
</dialog>
{% endblock content %}

project/templates/delete_post.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1 xmlns="http://www.w3.org/1999/html">Удаление объявления: {{ object.title }}</h1>
<hr>
<dialog open>
   <div>
            <form action="" method="post">
                {% csrf_token %}
                <p>Удаляем "{{ object.title }}"?</p>
                <p><input type="submit" value="Удалить" /></p>
            </form>

                <button onclick="window.location='http://127.0.0.1:8000/bulletin/'">Отменить</button>
   </div>
</dialog>
{% endblock content %}

project/templates/edit_comment_news.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Коментарий</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

project/templates/edit_post.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Объявление</h1>
<hr>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <br>
        {{form.media}}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

project/templates/post.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

<!-- Название у нас будет Product -->
{% block title %}
News
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}

<p></p>
   {% if post %}

           {% for new in post|dictsortreversed:"dateCreation"%}
            <html class="list-group-item">
                    <p><small class="fw-bold">{{ new.dateCreation|date:'d M Y' }}</small>
                       <small class="fw-bold"><a href="{% url 'post_detail' new.id %}">{{ new.title|censor}}</a></small></p>
            {% endfor %}


   {% else %}
       <h2>Объявлений нет, но вы держитесь!</h2>
   {% endif %}
    {# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

project/templates/post_created.html
<!DOCTYPE html>
<html lang="ru">
<head>
   <meta charset="UTF-8">
   <title>{{ title }}</title>
</head>
<body>
   <h2>Здравствуй, {{ user }}. Новая  <a href="{{ link }}"> статья </a> в твоём любимом разделе  </h2>
   <p>{{ text|truncatechars:50 }}</p>
</body>
</html>

project/templates/post_id.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
<!-- Название у нас будет Product -->

<html>

  <meta charset="utf-8">

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<!--<h1>{{ news }}</h1>-->
   <h2> {{ post.title|censor }} </h2>
<!--   <h3>{{ time_now|date:'M d Y' }}</h3>-->
   <!-- Если в переменной next_sale будет None,
   то выведется указанный в фильтре текст -->
<!--   <h3> {{ next_sale|default_if_none:"Чуть позже сообщим о распродаже!" }} </h3>-->

   <hr>
   {% if post %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
        <h4>{{post.dateCreation|date:'d M Y'}}</h4>
        <h4>

            <style>
                img {
                    border: 3px solid #808080;
                    }
            </style>

            <img
                src="{{ post.image.url}}" style="max-height:400px" align="left"
                style=" border: 20px solid #ffffff;"
            />

            <i>{{ post.text|censor|safe }}</i>
            {% if authenticate %}
                <p class="text-center"><a href="{% url 'response' post.id %}" class="btn btn-secondary btn-sm">Оставить отклик</a></p>
            {% endif %}
        </h4>
        <br><br><br>
        <ul class="list-group-flush">
                        </p>
        </ul>
    {% else %}
       <h2>Новостей нет, но вы держитесь!</h2>
   {% endif %}


{% endblock content %}

project/templates/profile.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load i18n %}


{% block content %}

    <h1>{{profile}}</h1>
    <h2>{{email}}</h2>
    {% if not authenticate.authenticate %}
        <a href="{% url 'authenticate' %}" class="btn btn-secondary btn-sm">Подтвердить почту</a></small>
    {% endif %}

    {% if authenticate.authenticate %}
        <p><a href="{% url 'post_create' %}" class="btn btn-secondary btn-sm">{% trans "Добавить объявление"%}</a></p>
    {%endif%}
    <p></p>
   {% if post %}

           {% for new in post|dictsortreversed:"dateCreation"%}
            <html class="list-group-item">
                    <p><small class="fw-bold">
                        <a href="{% url 'user_response' new.id %}" class="btn btn-secondary btn-sm">Откликов</a></small>
                    <small class="fw-bold">{{ new.dateCreation|date:'d M Y' }}</small>
                    <small class="fw-bold">{{ new.title|censor }}&nbsp;</small>
                        {% if perms.bulletin.add_post %}
                    <small class="fw-bold"><a href="{% url 'post_update' pk=new.id %}">Изменить</a>
                        {% endif %}
                        {% if perms.bulletin.add_post %}
                        <a href="{% url 'post_delete' pk=new.id %}">Удалить</a></small></p>
                        {% endif %}
            {% endfor %}


   {% else %}
       <h2>{% trans "У Вас пока нет объявлений."%}</h2>
   {% endif %}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

project/templates/response.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Коментарий</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

project/templates/send_mail.html
{% extends "admin/base_site.html" %}
{% block content %}
<h2>Введите текст для рассылки</h2>
    <form method="post">
    {% csrf_token %}
        {{ form.as_p }}
        <input  type="submit" value="Send">
    </form>
{% endblock %}

project/templates/send_news.html
<!DOCTYPE html>
<html lang="ru">
<head>
   <meta charset="UTF-8">
</head>
<body>
   <h2>{{message}}  </h2>
</body>
</html>

project/templates/send_response.html
<!DOCTYPE html>
<html lang="ru">
<head>
   <meta charset="UTF-8">
</head>
<body>
   <h2>Здравствуй, {{user}}.</h2>
   <h2>{{message}}  </h2>
   <ul>
         <li><a href="{{ link }}{{ post }}">Пройдите по ссылке, чтобы посмотреть объявление</a></li>
   </ul>
</body>
</html>

project/templates/successful_submission.html
{% extends "admin/base_site.html" %}
{% block content %}
<h2>Рассылка успешно отправлена!</h2>
{% endblock %}

project/templates/user_response.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block content %}
<h1>Отклики </h1>
<hr>

           {% for response in responses|dictsortreversed:"dateCreation"%}
            <html class="list-group-item">
                    <p class="fw-bold">
                    <small class="fw-bold">{{ response.dateCreation|date:'d M Y' }}</small>
                    <small class="fw-bold">{{ response.text|censor }}&nbsp;</small></p>
                    <p><small class="fw-bold">Отклик оставил: {{ response.commentUser }}&nbsp;</small>
                        {% if response.status %}
                            <a href="{% url 'accept_response' response.id %}" class="btn btn-secondary btn-sm">Отменить отклик</a>
                            {% else %}
                            <a href="{% url 'accept_response' response.id %}" class="btn btn-secondary btn-sm">Принять отклик</a>
                            <a href="{% url 'delete_response' response.id %}" class="btn btn-secondary btn-sm">Удалить отклик</a></p>
                        {% endif %}
            {% endfor %}
{% endblock content %}